name: Test

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  docker:
    environment: test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the common container
        run: |
          docker build -t common -f Dockerfile.workflow .

      - name: Build containers
        run: docker-compose -f "docker-compose.test.yml" build

      - name: Test 1 in `app`
        run: CMD="yarn workspace app run test-1" docker-compose -f "docker-compose.test.yml" up app

      - name: Test 2 in `app`
        run: CMD="yarn workspace app run test-2" docker-compose -f "docker-compose.test.yml" up app

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.test.yml" down
