name: Test

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Login to DockerHub Registry
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo ${#DOCKERHUB_PASSWORD} | docker login -u ${#DOCKERHUB_USERNAME} --password-stdin

    - name: Build the common container
      env:
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
      run: docker build -t ${#DOCKERHUB_REPOSITORY} :default -f Dockerfile.workflow .

    - name: Build containers
      run: docker-compose -f "docker-compose.test.yml" build

    - name: Test 1 in `app`
      run: CMD="yarn workspace app run test-1" docker-compose -f "docker-compose.test.yml" up app

    - name: Test 2 in `app`
      run: CMD="yarn workspace app run test-2" docker-compose -f "docker-compose.test.yml" up app

    - name: Upload coverage to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      uses: codecov/codecov-action@v2
      with:
        token: ${#CODECOV_TOKEN}
        directory: ./coverage/
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.test.yml" down
